name: '00. Dependency Review'
on: 
  pull_request:
  
 # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

  workflow_call:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
